#ifndef CONFIGS_H
#define CONFIGS_H

#define SUPPORTED_HASHING_ALGORITHMS          "SHA-224","SHA-256","SHA-384","SHA-512","MD4","MD5"
#define SUPPORTED_ENCRYPTION_ALGORITHMS       "AES","Serpent","Twofish","Camellia","ChaCha20"
#define SUPPORTED_BLOCK_CYPHER_KEY_SETTINGS   "128","192","256"
#define SUPPORTED_STREAM_CYPHER_KEY_SETTINGS  "256"
#define SUPPORTED_KEY_DERIVATION_FUNCTIONS    "PBKDF2","Scrypt","Argon2id"

#define WORDLISTS_RESOURCES_DIRECTORY         ":/Wordlists"
#define DATABASE_FILE_FILTER                  "PassForge Databases (*.pfdb)"

#define DATABASE_MIN_PASSWORD_LENGTH          8
#define DATABASE_DEFAULT_PASSWORD_ALGORITHM   "SHA-512"

#define KEY_DERIVATION_PBKDF2_MIN_ITERATIONS  100
#define KEY_DERIVATION_PBKDF2_MAX_ITERATIONS  1000000000
#define KEY_DERIVATION_PBKDF2_INIT_ITERATIONS 5000
#define KEY_DERIVATION_SCRYPT_MIN_ITERATIONS  1
#define KEY_DERIVATION_SCRYPT_MAX_ITERATIONS  5
#define KEY_DERIVATION_SCRYPT_INIT_ITERATIONS 3
#define KEY_DERIVATION_SCRYPT_COST_PARAM      13
#define KEY_DERIVATION_SCRYPT_BLOCK_SIZE      8
#define KEY_DERIVATION_SCRYPT_PARALLELIZATION 1
#define KEY_DERIVATION_ARGON2_MIN_ITERATIONS  1
#define KEY_DERIVATION_ARGON2_MAX_ITERATIONS  5
#define KEY_DERIVATION_ARGON2_INIT_ITERATIONS 3
#define KEY_DERIVATION_ARGON2_ALGORITHM_TYPE  2
#define KEY_DERIVATION_ARGON2_PARALLELISM     2
#define KEY_DERIVATION_ARGON2_MEMORY          262144

#define CIPHER_SETTINGS_AES                   "AES-%1/EAX"
#define CIPHER_SETTINGS_SERPENT               "Serpent-%1/EAX"
#define CIPHER_SETTINGS_TWOFISH               "Twofish-%1/EAX"
#define CIPHER_SETTINGS_CAMELLIA              "Camellia-%1/EAX"
#define CIPHER_SETTINGS_CHACHA20              "ChaCha20"

#endif // CONFIGS_H
